spring:
  config:
    activate:
      on-profile: home

  datasource:
    url: ${HOME_DB_URL:jdbc}
    username: ${HOME_DB_USER}
    password: ${HOME_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
